backend/urls.py
from django.urls import path
from backend import views

app_name = 'backend'

urlpatterns = [
    path('', views.login_view, name='login_view'),
    path('home/', views.index, name='index'),
    path('login-page/', views.login, name='login'),
    path('category-page/', views.categroy_form, name='categroy_form'),
    path('post-form/', views.post_form, name='post_form'),
    path('edit-post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('confirm-logout/', views.confirm_logout, name='confirm_logout'),
    path('logout-page/', views.logout_view, name='logout_view'),
    path('register-page/', views.register, name='register'),
    path('contact-page/', views.contact_form, name='contact_form')
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from frontend import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('pages/', include('frontend.urls')),
    path('dashboard/', include('backend.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/models.py
from django.db import models

# Create your models here.

backend/forms.py
from django import forms
from frontend.models import Category, Post
from django.core import validators
from django.contrib.auth.models import User
from backend.options import REFERER_FIELD, GENDER_FIELD, CHOOSE
from backend.functions import check_for_c
from frontend.models import ContactModel




class CategoryForm(forms.ModelForm):
    cat_name = forms.CharField(label="Category Name", 
               widget=forms.TextInput(
               attrs={'class':'form-control', 'placeholder':'Enter Category'}))
    cat_desc = forms.CharField(label='Description', required=False,
              widget=forms.Textarea(
             attrs={'class':'form-control'}
              ))
    catch_bot = forms.CharField(required=False, 
                widget=forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])
    # clean_<fieldname> is use to validate for just one field
    def clean_cat_name(self):
        cat = self.cleaned_data.get('cat_name')
        if Category.objects.filter(cat_name=cat).exists():
            raise forms.ValidationError(f'{cat} already exist')
        return cat

    class Meta():
        fields = '__all__'
        model = Category


class ContactForm(forms.ModelForm):
	name = forms.CharField(validators=[check_for_c], widget=forms.TextInput(
	    attrs={'class': 'form-control', 'placeholder': 'Enter Name'}))
	subject = forms.CharField(widget=forms.TextInput(
	    attrs={'class': 'form-control', 'placeholder': 'Enter Subject', 'max_length': 10}))
	email = forms.EmailField(widget=forms.EmailInput(
	    attrs={'class': 'form-control', 'placeholder': 'Enter Email'}))
	verify_email = forms.EmailField(label='Email Again', widget=forms.EmailInput(
	    attrs={'class': 'form-control', 'placeholder': 'Enter Email'}))
	gender = forms.ChoiceField(widget=forms.RadioSelect(), choices=GENDER_FIELD)
	referer = forms.ChoiceField(required=False, widget=forms.Select(
	    attrs={'class': 'form-control'}), choices=REFERER_FIELD)
	message = forms.CharField(required=False, widget=forms.Textarea(
	    attrs={'class': 'form-control'}))
	botcatcher = forms.CharField(widget=forms.HiddenInput(
	), required=False, validators=[validators.MaxLengthValidator(0)])

	# To validate just one field

	def clean_subject(self):
		subt = self.cleaned_data.get('subject')
		if 'Hello' not in subt:
			raise forms.ValidationError('You must include "Hello" in your subject')
		return subt

	# TO validate two fields (Fields that depend on each other)
	def clean(self):
		cleaned_data = super().clean()
		email1 = cleaned_data.get('email')
		email2 = cleaned_data.get('verify_email')
		if email1 != email2:
			self.add_error('email', 'The two emails must match')
		elif not email1.endswith('@alabiansolutions.com'):
			self.add_error('email', 'Your email must end with "@alabiansolutions"')

	class Meta():
		model = ContactModel
		fields = ('name', 'subject', 'email', 'verify_email',
		          'gender', 'referer', 'message')

class PostForm(forms.ModelForm):
    pst_title = forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Post Title'})
    )
    pst_content = forms.CharField(
        widget=forms.Textarea(attrs={'class':'form-control'})
    )
    pst_img = forms.ImageField()
    category = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(), 
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}))
    user = forms.ModelChoiceField(
        queryset=User.objects.all(), empty_label='Please Choose', 
        widget=forms.Select(attrs={'class': 'form-control'}))
    featured = forms.BooleanField(required=False)

    class Meta():
        exclude = ['created', ]
        model = Post

backend/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from frontend.models import Post, Category

from backend.forms import CategoryForm, PostForm, ContactForm

from django.conf import settings

from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags

# Create your views here.

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('backend:index')
        else:
            messages.error(request, 'Username and Password do not match')
    return render(request, 'frontend/login.html')

@login_required(login_url='/dashboard/')
def confirm_logout(request):
    return render(request, 'backend/confirm.html')

@login_required(login_url='/dashboard/')
def logout_view(request):
    logout(request)
    return redirect('backend:login_view')

@login_required(login_url='/dashboard/')
def index(request):
    return render(request, 'backend/index.html')

def register(request):
    return render(request, 'frontend/register.html')

@login_required(login_url='/dashboard/')
def categroy_form(request):
    if request.method == 'POST':
        cat_form = CategoryForm(request.POST)
        if cat_form.is_valid():
            cat_form.save()
            messages.success(request, 'Category Created')
    else:
        cat_form = CategoryForm()
    return render(request, 'backend/add-category.html', {'cat':cat_form})

@login_required(login_url='/dashboard/')
def post_form(request):
    if request.method == 'POST':
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            post_form.save()
            messages.success(request, 'Post Created')
    else:
        post_form = PostForm()
    return render(request, 'backend/add-post.html', {'post': post_form})


def contact_form(request):
    if request.method == 'POST':
        contform = ContactForm(request.POST)
        if contform.is_valid():
            contform.save()
            subject = contform.cleaned_data.get('subject')
            name = contform.cleaned_data.get('name')
            email = contform.cleaned_data.get('email')
            gender = contform.cleaned_data.get('gender')
            referer = contform.cleaned_data.get('referer')
            my_dict = {'name':name, 'email':email, 'gender':gender, 'referer':referer}
            html_message = render_to_string('frontend/mail-template.html', my_dict)
            plain_message = strip_tags(html_message)
            from_email = settings.EMAIL_HOST_USER
            mail.send_mail(subject, plain_message, from_email, ['uwazie.benedict@alabiansolutions.com',], html_message=html_message)
            messages.success(request, 'Form is saved')
    else:
        contform = ContactForm()
    return render(request, 'frontend/contact.html', {'con': contform})


@login_required(login_url='/dashboard/')
def edit_post(request, post_id):
    single_post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        post_form = PostForm(request.POST, request.FILES, instance=single_post)
        if post_form.is_valid():
            post_form.save()
            messages.success(request, 'Post Edited')
    else:
        post_form = PostForm(instance=single_post)
    return render(request, 'backend/edit-post.html', {'edit_post': post_form})
    

templates/backend/add-category.html
{% extends 'backend/base.html' %}
{% load static %}

{% block title %}
Add Categeroy
{% endblock %}

{% block content %}
<h2>Add Categeroy</h2>

<form method="POST">
    {% include 'backend/form-snippet.html' with form=cat %}
    <input type="submit" value="Add Category" class="btn btn-warning">
</form>
{% endblock %}

templates/backend/add-post.html
{% extends 'backend/base.html' %}
{% load static %}

{% block title %}
Add Post
{% endblock %}

{% block content %}
<h2>Add Categeroy</h2>

<form method="POST" enctype="multipart/form-data">
    {% include 'backend/form-snippet.html' with form=post %}
    <input type="submit" value="Add Post" class="btn btn-warning">
</form>
{% endblock %}

templates/backend/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
		{% block title %}
		{% endblock %}
	</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'backend/css/bootstrap.min.css' %}">
    <link href="{% static 'backend/css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'backend/css/style.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  	<div class="container-fluid">
  		<div class="row">
  			{% include 'backend/sidebar.html' %}
  			<div class="col-sm-10">
  				<div class="row">
  					<div class="col-sm-12  pt-4 pb-4" id="topBar">
  						<a class="text-white">
  							<span class="float-right name">Uwazie Benedict</span>
  						</a>
  					</div>
				</div>
				<div class="row">
					<div class="col-sm-12">	
						{% block content %}
						{% endblock %}
					</div>
				</div>
				  
  				
  			</div>
  		</div>
  	</div>
    
	<script src="{% static 'backend/js/jquery-3.3.1.slim.min.js' %}"></script>
	<script src="{% static 'backend/js/popper.min.js' %}"></script>
	<script src="{% static 'backend/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/backend/confirm.html
{% extends 'backend/base.html' %}
{% load static %}

{% block title %}
Home
{% endblock %}

{% block content %}
<h2>Do you really want to logout</h2>
<a href="{% url 'backend:logout_view' %}">Logout</a>
{% endblock %}

templates/backend/edit-post.html
{% extends 'backend/base.html' %}
{% load static %}

{% block title %}
Edit Post
{% endblock %}

{% block content %}
<h2>Edit Post </h2>

<form method="POST" enctype="multipart/form-data">
    {% include 'backend/form-snippet.html' with form=edit_post %}
    <input type="submit" value="Edit Post" class="btn btn-warning">
</form>
{% endblock %}

templates/backend/index.html
{% extends 'backend/base.html' %}
{% load static %}

{% block title %}
Home
{% endblock %}

{% block content %}
<h2>Dashboard</h2>
{% endblock %}

templates/backend/sidebar.html
{% load static %}
<div class="col-sm-2 bg-dark h-100 pt-2 bg-warning" id="sideBar">
    <img src="{% static 'backend/images/logo.png' %}" alt="" class="img-fluid">
    <hr class="bg-white">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link active text-white" href="{% url 'backend:post_form' %}">Add Post</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="#">View Post</a>
        </li>

    </ul>
    <hr class="bg-white">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link active text-white" href="{% url 'backend:categroy_form' %}">Add Category</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="#">View Category</a>
        </li>

    </ul>
    <hr class="bg-white">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link active text-white" href="#">Change Password</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="#">View Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="#">Edit Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'backend:confirm_logout' %}">Logout</a>
        </li>

    </ul>
    <hr class="bg-white">
</div>