backend/urls.py
from django.urls import path
from backend import views

app_name = 'backend'

urlpatterns = [
    path('', views.login_view, name='login_view'),
    path('home/', views.index, name='index'),
    path('login-page/', views.login, name='login'),
    path('category-page/', views.categroy_form, name='categroy_form'),
    path('post-form/', views.post_form, name='post_form'),
    path('edit-post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('confirm-logout/', views.confirm_logout, name='confirm_logout'),
    path('logout-page/', views.logout_view, name='logout_view'),
    path('register-page/', views.register, name='register'),
    path('contact-page/', views.contact_form, name='contact_form')
]

frontend/urls.py
from django.urls import path
from frontend import views

app_name = 'frontend'

urlpatterns = [
     path('', views.about, name='about'),
    path('service-page/', views.service, name='service'),
    path('post-list/', views.all_post, name='all_post'),
    path('post-cat/<int:cat_id>/', views.post_from_cat, name='post_from_cat'),
    path('single-post/<int:post_id>/', views.single_post, name='single_post'),
    path('users/', views.users, name='users'),

]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from frontend import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('pages/', include('frontend.urls')),
    path('dashboard/', include('backend.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/models.py
from django.db import models
from django.contrib.auth.models import User
from backend.options import REFERER_FIELD, GENDER_FIELD, CHOOSE

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.IntegerField(blank=True, null=True)
    profile_pic = models.FileField(blank=True, null=True, upload_to='upload/')


class Category(models.Model):
    cat_name = models.CharField(max_length=100, verbose_name='Category')
    cat_desc = models.TextField(blank=True, null=True, verbose_name='Category Description')

    def __str__(self):
        return self.cat_name

    class Meta():
        verbose_name_plural='Category'


class Post(models.Model):
    pst_title = models.CharField(max_length=100)
    pst_content = models.TextField()
    pst_img = models.FileField(blank=True, null = True, upload_to='upload/')
    category = models.ManyToManyField(Category)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    featured = models.BooleanField(default=False, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.pst_title

    class Meta():
        verbose_name_plural='Post'


class Service(models.Model):
    srv_title = models.CharField(max_length=100)
    srv_content = models.TextField()

    def __str__(self):
        return self.srv_title


class ContactModel(models.Model):
    
	name = models.CharField(max_length=120)
	subject = models.CharField(max_length=120)
	email = models.EmailField()
	gender = models.CharField(max_length=15, choices=GENDER_FIELD)
	referer = models.CharField(
	    max_length=30, choices=REFERER_FIELD, default=CHOOSE, null=True, blank=True)
	message = models.TextField(null=True, blank=True)

	def __str__(self):
		return self.name

frontend/views.py
from django.shortcuts import render
from django.http import HttpResponse
from frontend.models import Post, Category, Service
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def index(request):
    home_post = Post.objects.filter(featured=True).order_by('-created')[:3]
    home_serv = Service.objects.all()[:3]
    args = {'home_post':home_post, 'home_serv':home_serv}
    return render(request, 'frontend/index.html', args)

def about(request):
    return render(request, 'frontend/about.html')


def all_post(request):
	all_post = Post.objects.all()
	return render(request, 'frontend/post-list.html', {'posts':all_post})

def post_from_cat(request, cat_id):
	post_cat = Post.objects.filter(category__id=cat_id)
	return render(request, 'frontend/posts-cat.html', {'post_cat':post_cat})


def single_post(request, post_id):
    try:
        single = Post.objects.get(id=post_id)
        return render(request, 'frontend/single-post.html', {'single_post': single})
    except ObjectDoesNotExist:
        return render(request, 'frontend/404.html')
    




def contact(request):
    return render(request, 'frontend/contact.html')


def service(request):
    serv = Service.objects.all()
    return render(request, 'frontend/services.html', {'sv':serv})


def users(request):
    return render(request, 'frontend/users.html')

templates/frontend/about.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block title %}
About
{% endblock %}

{% block content %}
<section id="sectionTitle">
  <div class="pageTitle">
    <h1>About Us</h1>
  </div>
</section>
<!-- END OF PAGE TITLE -->
<section id="content">
  <div class="row">
    <div class="col-sm-9 text-center" id="mainContent">
      <div class="row">
        <div class="col-sm-4">
          <a href="detail.html">
            <img src="{% static 'frontend/images/mark.jpg' %}" class="img-circle">
          </a>
          <h2>Mark Zuckerbarg</h2>
          <a href="detail.html" class="btn btn-primary">Readmore</a>
        </div>
        <div class="col-sm-4">
          <a href="detail.html">
            <img src="{% static 'frontend/images/jerry.jpg' %}" class="img-circle">
          </a>
          <h2>Jerry Jang</h2>
          <a href="detail.html" class="btn btn-primary">Readmore</a>
        </div>
        <div class="col-sm-4">
          <a href="detail.html">
            <img src="{% static 'frontend/images/mayer.jpg' %}" class="img-circle">
          </a>
          <h2>Marrissa Mayer</h2>
          <a href="detail.html" class="btn btn-primary">Readmore</a>
        </div>
      </div>
    </div>
    {% include 'frontend/sidebar.html' %}
  </div>
</section>
{% endblock %}

templates/frontend/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link href="{% static 'frontend/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/css/style.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="container">
      <header id="siteLogo">
        <div class="row">
          <div class="col-sm-3">
            <a href="{% url 'index' %}">
              <img src="{% static 'frontend/images/logo.png' %}">
            </a>
          </div>
          <div class="col-sm-9">
            <span class="social-logo pull-right">
              <a href="#">
                <img src="{% static 'frontend/images/fb.png' %}" class="img-circle">
              </a>
              <a href="#">
                <img src="{% static 'frontend/images/tw.png' %}" class="img-circle">
              </a><a href="#">
                <img src="{% static 'frontend/images/gp.png' %}" class="img-circle">
              </a>
            </span>
          </div>
        </div>
      </header>
      <!-- END OF SITE LOGO ROW -->
      <section id="siteMenu">
        <div class="row">
          <nav class="navbar navbar-inverse">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-target="#mainNav" data-toggle="collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div class="collapse navbar-collapse" id="mainNav">
              {% url 'index' as home%}
              {% url 'frontend:about' as about %}
              {% url 'frontend:service' as srv%}
              {% url 'frontend:all_post' as al  %}
              {% url 'backend:login_view' as log  %}
              {% url 'backend:register' as register  %}
              {% url 'backend:contact_form' as contact  %}
              {% url 'frontend:users' as usr  %}

              <ul class="nav navbar-nav">
                <li {% if request.path == home %} class="active" {% endif %}><a href="{% url 'index' %}">Home</a></li>
                <li  {% if request.path == about %} class="active" {% endif %}><a href="{% url 'frontend:about' %}">About</a></li>
                <li {% if request.path == usr %} class="active" {% endif %}><a href="{% url 'frontend:users' %}">Users</a>
                </li>
                <li {% if request.path == al %} class="active" {% endif %}><a href="{% url 'frontend:all_post' %}">Blog</a></li>
                {% for c in cat %}
                    <li><a href="{% url 'frontend:post_from_cat' c.id %}">{{ c.cat_name }}</a></li>

                {% endfor %}
                <li  {% if request.path == srv %} class="active" {% endif %}><a href="{% url 'frontend:service' %}">Services</a></li>
                <li {% if request.path == log %} class="active" {% endif %}><a href="{% url 'backend:login_view' %}">Login</a></li>
                <li {% if request.path == register %} class="active" {% endif %}><a href="{% url 'backend:register' %}">Register</a></li>
                <li {% if request.path == contact %} class="active" {% endif %}><a href="{% url 'backend:contact_form' %}">Contact</a>
                                </li>
              </ul>
            </div>
          </nav>
        </div>
      </section>
      <!-- END OF SITE MENU -->
      {% block content %}
      {% endblock %}
    </div>
    <footer class="container-fluid" id="siteFooter">
      <div class="row">
        <div class="col-sm-4">
          <h4>Menu</h4>
          <ul class="nav">
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div>
        <div class="col-sm-4">
          <h4>Services</h4>
          <ul class="nav">
            <li><a href="#">Web Development</a></li>
            <li><a href="#">Software Development</a></li>
            <li><a href="#">Mobile App Development</a></li>
            <li><a href="#">Training</a></li>
          </ul>
        </div> 
        <div class="col-sm-4">
          <h4>Branches</h4>
          <ul class="nav">
            <li><a href="#">Ikeja</a></li>
            <li><a href="#">Festac</a></li>
            <li><a href="#">Surulere</a></li>
            <li><a href="#">Lekki</a></li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <p>&copy; {{ d|date:'Y' }}</p>
        </div>
        <div class="col-md-9">
          <p class="copy pull-right">
            <a href="#" target="_blank">www.alabiansolutions.com</a>
          </p>
        </div>
      </div>
    </footer>

    <script src="{% static 'frontend/js/jquery.js' %}"></script>
    <script src="{% static 'frontend/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/frontend/contact.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block title %}
Contact
{% endblock %}

{% block content %}
<section id="sectionTitle">
  <div class="pageTitle">
    <h1>Contact</h1>
  </div>
</section>
<!-- END OF PAGE TITLE -->
<section id="content">
  <div class="row">
    <div class="col-sm-9" id="mainContent">
      <div class="row">
        <div class="col-sm-12">
          <form method="POST">
            {% include 'backend/form-snippet.html' with form=con %}
            <input type="submit" class="btn btn-success" value="Send">
          </form>
        </div>
      </div>
    </div>
    {% include 'frontend/sidebar.html' %}
  </div>
</section>
{% endblock %}

templates/frontend/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>About</title>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="container">
      <header id="siteLogo">
        <div class="row">
          <div class="col-sm-3">
            <img src="images/logo.png">
          </div>
          <div class="col-sm-9">
            <span class="social-logo pull-right">
              <a href="#">
                <img src="images/fb.png" class="img-circle">
              </a>
              <a href="#">
                <img src="images/tw.png" class="img-circle">
              </a><a href="#">
                <img src="images/gp.png" class="img-circle">
              </a>
            </span>
          </div>
        </div>
      </header>
      <!-- END OF SITE LOGO ROW -->
      <section id="siteMenu">
        <div class="row">
          <nav class="navbar navbar-inverse">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-target="#mainNav" data-toggle="collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div class="collapse navbar-collapse" id="mainNav">
              <ul class="nav navbar-nav">
                <li><a href="index.html">Home</a></li>
                <li class="active"><a href="about.html">About</a></li>
                <li><a href="post-list.html">Blog</a></li>
                <li><a href="services.html">Services</a></li>
                <li><a href="contact.html">Contact</a></li>
              </ul>
            </div>
          </nav>
        </div>
      </section>
      <!-- END OF SITE MENU -->
      <section id="sectionTitle">
        <div class="pageTitle">
          <h1>About Us</h1>
        </div>
      </section>
      <!-- END OF PAGE TITLE -->
      <section id="content">
        <div class="row">
          <div class="col-sm-9 text-center" id="detailContent">
              <div class="contain-img">
                <div class="img-div">
                    <img src="images/mark.jpg" class="img-responsive">
                </div>
              </div>
              <div class="detail-content">
                <h2>Mark Zuckerbarg</h2>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque earum,
                  possimus, hic quibusdam aliquam sit natus aut fugiat sapiente, odio fuga
                  debitis reiciendis, pariatur officiis non consequuntur harum illum! Delectus!
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque earum,
                  possimus, hic quibusdam aliquam sit natus aut fugiat sapiente, odio fuga
                  debitis reiciendis, pariatur officiis non consequuntur harum illum! Delectus!
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque earum,
                  possimus, hic quibusdam aliquam sit natus aut fugiat sapiente, odio fuga
                  debitis reiciendis, pariatur officiis non consequuntur harum illum! Delectus!
                </p>
              </div>

          </div>
          <aside class="col-sm-3" id="sideBar">
            <div class="widget">
              <h3>Menu</h3>
              <ul class="nav">
                <li><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Contact</a></li>
              </ul>
            </div>
            <div class="widget">
              <h3>Branches</h3>
              <ul class="nav">
                <li><a href="#">Ikeja</a></li>
                <li><a href="#">Festac</a></li>
                <li><a href="#">Surulere</a></li>
                <li><a href="#">Lekki</a></li>
              </ul>
            </div>
          </aside>
          <!-- END OF ASIDE CONTENT -->
        </div>
      </section>
    </div>
    <footer class="container-fluid" id="siteFooter">
      <div class="row">
        <div class="col-sm-4">
          <h4>Menu</h4>
          <ul class="nav">
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div>
        <div class="col-sm-4">
          <h4>Services</h4>
          <ul class="nav">
            <li><a href="#">Web Development</a></li>
            <li><a href="#">Software Development</a></li>
            <li><a href="#">Mobile App Development</a></li>
            <li><a href="#">Training</a></li>
          </ul>
        </div>
        <div class="col-sm-4">
          <h4>Branches</h4>
          <ul class="nav">
            <li><a href="#">Ikeja</a></li>
            <li><a href="#">Festac</a></li>
            <li><a href="#">Surulere</a></li>
            <li><a href="#">Lekki</a></li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <p>&copy; 2016</p>
        </div>
        <div class="col-md-9">
          <p class="copy pull-right">
            <a href="#" target="_blank">www.alabiansolutions.com</a>
          </p>
        </div>
      </div>
    </footer>

    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

templates/frontend/form-snippet.html
{% if messages %}
    {% for m in messages %}
    <div class="alert alert-success">{{ m }}</div>
    {% endfor %}
{% endif %}

{% for field in form.hidden_fields %}
    {% if field.errors %}
        {% for ferror in field.errors %}
            <div class="alert alert-danger">{{ ferror }}</div>
        {% endfor %}
    {% endif %}
    <!-- This shows hidden field on inspect -->
    {{ field }}

{% endfor %}

{% for  field in form.visible_fields %}
        {% if field.errors %}
            {% for ferror in field.errors %}
            <div class="alert alert-danger">{{ ferror }}</div>
            {% endfor %}
        {% endif %}

        <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
        </div>
{% endfor %}
{% csrf_token %}

templates/frontend/index.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block title %}
Home
{% endblock %}

{% block content %}
<section id="banner">
  <div class="row">
    <div class="col-sm-3 col-sm-offset-9 text-center">
      <div class="caption">
        <h1>Join Us</h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet minus, esse ex molestias maiores. Provident
          nam totam modi, expedita quos sit voluptates distinctio porro illo esse asperiores, animi eveniet ipsam?
        </p>
        <a href="#" class="btn btn-primary">Readmore</a>
      </div>
    </div>
  </div>
</section>
<section id="services" class="text-center">
  <div class="page-header">
    <h1>Services</h1>
  </div>
  <div class="row">
    {% if home_serv %}
      {% for hm in home_serv %}
        <div class="col-sm-4">
          <span class="fa fa-android"></span>
          <h1>{{ hm.srv_title }}</h1>
          <p>
            {{ hm.srv_content }}
          </p>
          <a href="#" class="btn btn-primary">Readmore</a>
        </div>
      {% endfor %}

    {% endif %}
   
   
  </div>
</section>

<section id="post" class="text-center">
  <div class="page-header">
    <h1>Featured Post</h1>
  </div>
  <div class="row">
    {% if home_post %}
    {% for hp in home_post %}
         {% if hp.featured %}
            <div class="col-sm-4">
              <img src="{{ hp.pst_img.url }}" class="img-responsive" alt="">
              <h1>{{ hp.pst_title }}</h1>
              <p>
                {{ hp.pst_content }}
              </p>
              <a href="{% url 'frontend:single_post' hp.id %}" class="btn btn-primary">Readmore</a>
            </div>
         {% endif %}
    {% endfor %}

    {% endif %}


  </div>
</section>
<!-- END OF SERVICE SECTION -->
{% endblock %}

templates/frontend/login.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block title %}
Login
{% endblock %}

{% block content %}
<section id="sectionTitle">
  <div class="pageTitle">
    <h1>Login</h1>
  </div>
</section>
<!-- END OF PAGE TITLE -->
<section id="content">
  <div class="row">
    <div class="col-sm-9" id="mainContent">

      {% if messages %}
        {% for mes in messages %}
        <div class="alert alert-danger">{{ mes }}</div>
        {% endfor %}
      {% endif %}
     <form method="POST">
         <div class="form-group">
             <label>Username</label>
             <input type="text" class="form-control" name="username" placeholder="Username">
         </div>
        <div class="form-group">
            <label>Password</label>
            <input type="password" class="form-control" name="password" placeholder="Password">
        </div>
        <input type="submit" value="Login" class="btn btn-warning">
        {% csrf_token %}
     </form>
    </div>
    {% include 'frontend/sidebar.html' %}
  </div>
</section>
{% endblock %}

templates/frontend/mail-template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


    <p>Name: {{ name }}</p>
    <p>Subject: {{ subject }}</p>
    <p>Gender: {{ gender }}</p>
    <p>Referer: {{ referer }}</p>
    
</body>
</html>

templates/frontend/post-list.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block title %}
Post List
{% endblock %}

{% block content %}
 <section id="sectionTitle">
        <div class="pageTitle">
          <h1>5 Post From Sports Category</h1>
        </div>
      </section>
      <!-- END OF PAGE TITLE -->
      <section id="content">
        <div class="row">
          <div class="col-sm-9" id="mainContent">
             {% if posts %}
                {% for p in posts %}
                    <div class="row">
                      <div class="col-sm-9" id="mainContent">
                        <div class="row">
                          <div class="col-md-4 col-sm-4">
                            <div class="thumbnail">
                              <img src="{{ p.pst_img.url }}">
                            </div>
                          </div> 
                          <div class="col-md-8 col-sm-8">
                            <div class="blog-content">
                               <p>
                                Time:{{ p.created|date:'H:i a' }}, 
                                Category:
                                  {% for q in p.category.all  %}
                                  <a href="{% url 'frontend:post_from_cat' q.id %}">{{ q.cat_name }}</a>,
                                  {% endfor %}

                                
                                Posted By: <a href="#">{{ p.user.username }}</a>.
                                
                              </p>
                              <h2>{{ p.pst_title }}</h2>
                              <p>
                               {{ p.pst_content|truncatewords:25 }}
                              </p>
                              <a href="{% url 'frontend:single_post' p.id %}" class="btn btn-success">Readmore</a>
                            </div>
                          </div>
                        </div>
                        <!-- END OF BLOG ROW 1 -->
                       
                      </div>
                      <!-- END OF ASIDE CONTENT -->
                    </div>
                {% endfor %}
              {% endif %}
          </div>
          {% include 'frontend/sidebar.html' %}
        </div>

       
        
      </section>
{% endblock %}

templates/frontend/posts-cat.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block title %}
Post List
{% endblock %}

{% block content %}
 <section id="sectionTitle">
        <div class="pageTitle">
          <h1>5 Post From Sports Category</h1>
        </div>
      </section>
      <!-- END OF PAGE TITLE -->
      <section id="content">
        <div class="row">
          <div class="col-sm-9" id="mainContent">
             {% if post_cat %}
                {% for p in post_cat %}
                    <div class="row">
                      <div class="col-sm-9" id="mainContent">
                        <div class="row">
                          <div class="col-md-4 col-sm-4">
                            <div class="thumbnail">
                              <img src="{{ p.pst_img.url }}">
                            </div>
                          </div> 
                          <div class="col-md-8 col-sm-8">
                            <div class="blog-content">
                               <p>
                                Time:{{ p.created|date:'H:i a' }}, 
                                Category:
                                  {% for q in p.category.all  %}
                                  <a href="{% url 'frontend:post_from_cat' q.id %}">{{ q.cat_name }}</a>,
                                  {% endfor %}

                                
                                Posted By: <a href="#">{{ p.user.username }}</a>.
                                
                              </p>
                              <h2>{{ p.pst_title }}</h2>
                              <p>
                               {{ p.pst_content|truncatewords:30 }}
                              </p>
                              <a href="{% url 'frontend:single_post' p.id %}" class="btn btn-success">Readmore</a>
                            </div>
                          </div>
                        </div>
                        <!-- END OF BLOG ROW 1 -->
                       
                      </div>
                      <!-- END OF ASIDE CONTENT -->
                    </div>
                {% endfor %}
              {% else %}
                    <h2>No Data found </h2>
              {% endif %}
          </div>
          {% include 'frontend/sidebar.html' %}
        </div>

       
        
      </section>
{% endblock %}

templates/frontend/register.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block title %}
Register
{% endblock %}

{% block content %}
<section id="sectionTitle">
  <div class="pageTitle">
    <h1>Register</h1>
  </div>
</section>
<!-- END OF PAGE TITLE -->
<section id="content">
  <div class="row">
    <div class="col-sm-9" id="mainContent">
    </div>
    {% include 'frontend/sidebar.html' %}
  </div>
</section>
{% endblock %}

templates/frontend/services.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block title %}
Service 
{% endblock %}

{% block content %}
<section id="sectionTitle">
  <div class="pageTitle">
    <h1>Services</h1>
  </div>
</section>
<!-- END OF PAGE TITLE -->
<section id="content">
  <div class="row">
    <div class="col-sm-9 text-center" id="mainContent">
      <div class="row">
        {% if sv %}
          {% for sr in sv %}
            <div class="col-sm-4">
              <span class="fa fa-android"></span>
              <h1>{{ sr.srv_title }}</h1>
              <p>
                {{ sr.srv_content| truncatewords:30 }}
              </p>
              <a href="#" class="btn btn-primary">Readmore</a>
            </div>
          {% endfor %}

        {% endif %}
       
        
      </div>
    </div>
    {% include 'frontend/sidebar.html' %}
  </div>
</section>
{% endblock %}

templates/frontend/sidebar.html
<aside class="col-sm-3" id="sideBar">
    <div class="widget">
        <h3>Search Site</h3>
        <form>
            <div class="form-group">
                <input type="text" name="search" class="form-control" placeholder="Search Site">
            </div>
            <button type="submit" class="btn btn-warning btn-block">Search</button>
        </form>
    </div>
    <div class="widget">
        <h3>Categories</h3>
        <ul class="nav">
            <li><a href="#">Sports <span class="badge pull-right">3</span></a></li>
            <li><a href="#">Entertainment <span class="badge pull-right">5</span></a></li>
            <li><a href="#">Business <span class="badge pull-right">7</span></a></li>
            <li><a href="#">Fashion <span class="badge pull-right">9</span></a></li>
        </ul>
    </div>
    <div class="widget">
        <h3>Branches</h3>
        <ul class="nav">
            <li><a href="#">Ikeja</a></li>
            <li><a href="#">Festac</a></li>
            <li><a href="#">Surulere</a></li>
            <li><a href="#">Lekki</a></li>
        </ul>
    </div>
</aside>
<!-- END OF ASIDE CONTENT -->